





// This file was generated by a tool. Any changes made manually will be lost
// the next time this project is built (via AssemblyFileVersion.tt).
using System.Reflection;

[assembly: AssemblyVersion("1.9.0.46")]
[assembly: AssemblyFileVersion("1.9.0.46")]
[assembly: AssemblyCopyright("Copyright © 2017 Kindel Systems, LLC.")]
 