// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 
namespace MCEControl {
    public partial class TelemetryService {
        public const string Key = "26132385-0150-4dd1-83da-ef861e0aee67";
    }
}
