// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 
namespace MCEControl {
    public partial class TelemetryService {
        public const string Key = "";
   }
}
